version: '3.8'

services:
  flask:
    build: ./src    
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=services/app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres_flask:postgres_flask@db:5432/postgres_flask_dev
      - SECRET_KEY=x!A%D*G-JaNdRgUkXp2s
    depends_on:
      db:
        condition: service_healthy   
    networks:
        flask_network:
          aliases:
            - flask.local

  db:
      image: postgres:13-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      ports:
      - 5432:5432
      environment:
        - POSTGRES_USER=postgres_flask
        - POSTGRES_PASSWORD=postgres_flask
        - POSTGRES_DB=postgres_flask_dev
      restart: always
      healthcheck:
        test: ["CMD", "pg_isready","-d", "postgres_flask_dev","-U", "postgres_flask"]
        interval: 5s
        retries: 5
      networks:
        flask_network:
          aliases:
            - postgres.local

volumes:
  postgres_data:

networks:
  flask_network:
    driver: bridge