version: '3.8'

services:
  flask:
    build: ./src
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=services/app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - SECRET_KEY=x!A%D*G-JaNdRgUkXp2s
    depends_on:
      db:
        condition: service_healthy
    networks:
      flask_network:
        aliases:
          - flask.local

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "postgres",
          "-U",
          "postgres"
        ]
      interval: 5s
      retries: 5
    networks:
      flask_network:
        aliases:
          - postgres.local

  pgadmin:
    container_name: pgadmincontainer
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      flask_network:
        aliases:
          - pgadmin.local

volumes:
  postgres_data:


networks:
  flask_network:
    driver: bridge
